### ISSUE TITLE
recommendModal.tsx useEffect() 부분 수정 요청

### ISSUE THREAD

**Issue by YouJin-Cho** [Team-FAB/FAB-FE#170]
아래 사진은 recommendModal.tsx 부분입니다. 
useEffect를 리렌더링 하도록 설정한 'userProfile' 부분을 밖으로 빼어 주석 처리하였습니다.
'userProfile'이 포함될 경우, 프로필 모달창이 열려있는 동안 계속해서 리렌더링 해오기 때문에 불필요한 렌더링이 발생합니다. 
아래 사진 참고 부탁드립니다 ☺️

![스크린샷 2023-06-22 오후 5 40 56](https://github.com/Team-FAB/FAB-FE/assets/122290134/2df43609-d95b-47a2-95e1-02a759ab04d4)

**Comment by HwangJiMinn** [comment]
recommendModal이 visible 되었을 때만 랜더링 되게 수정하였습니다.

![캡처](https://github.com/Team-FAB/FAB-FE/assets/122066788/8ea6b379-c23f-4b9e-a1d1-ea808f55fa94)
