### ISSUE TITLE
리액트 렌더링 최적화

### ISSUE THREAD

**Issue by kwonseona** [Team-FAB/FAB-FE#66]
useMemo 혹은 useCallback을 사용하여 렌더링을 최적화를 진행해야합니다.
최적화를 진행해야하는 부분은
1. 룸메이트 구해요 페이지 - 게시글 검색 필터링
2. 마이페이지 - 찜한 목록(찜하기)

이 외 렌더링를 최적화 해야하는 부분이 있으면 말씀해주세요 :)

**Comment by YouJin-Cho** [comment]
useCallback 부분을 redux 관리로 대체하였습니다.
