### ISSUE TITLE
모달창 visible 오류

### ISSUE THREAD

**Issue by YouJin-Cho** [Team-FAB/FAB-FE#73]
## postModal.tsx visible 오류

* postModal이 화면에 표시될 때, visible 오류가 발생합니다. 아래 캡처 사진 참고 부탁드립니다! @HwangJiMinn 

![스크린샷 2023-06-09 오후 8 12 05](https://github.com/Team-FAB/FAB-FE/assets/122290134/a476b066-fd63-43c1-b205-11c1c2562b97)

**Comment by kwonseona** [comment]
![image](https://github.com/Team-FAB/FAB-FE/assets/119383369/75a9226a-6fbf-48d2-bd36-fa9506414a58)
이 부분 참고하시면 될 것 같습니다!!
@HwangJiMinn
