### ISSUE TITLE
공통 컴포넌트 PostCard 수정

### ISSUE THREAD

**Issue by YouJin-Cho** [Team-FAB/FAB-FE#86]
* PostCard 재사용 페이지 추가 
  - myPage의 favorite
  - myPage의 board
  
1. fetch 형식
  : link와 token의 유무에 따라 불러오는 fetch API 주소를 다르게 설정하였습니다. 

2. postsToShow.length = 0
 : postsToShow가 0일 경우, "글이 존재하지 않습니다."로 화면 표시를 통일하였습니다. 
  (적용 page : favorite, board, roomMate, mainPage)

**Comment by kwonseona** [comment]
지민님은 따로 사용하시구 계실거에여!! 지민님도 통일해서 사용하도록 변경하셔야할 것 같습니다😊
@HwangJiMinn

**Comment by YouJin-Cho** [comment]
PostCard에 적용되어 있는 기능들을 새로운 파일에 작성 후, props로 전달하였습니다.
